services: 
  flask-app:
    container_name: flask-app
    build:
      context: .
      dockerfile: dockerfile
    expose:
      - "5050"
    volumes:
      - .:/app
  nginx:
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    ports:
      - "443:443"
      - "81:80"
    depends_on:
      - flask-app  # tu backend Flask
  
    
