entryPoints:
  web:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: websecure
          scheme: https
          permanent: true
  websecure:
    address: ":443"
    http:
      tls: {}

providers:
  file:
    filename: /dynamic/tls.yaml
  docker:
    exposedByDefault: false
    network: proxy

api:
  dashboard: true
  insecure: false

log:
  level: INFO
accessLog: {}
metrics:
  prometheus: {} 